services:

  # hivemetastore:
  #   platform: linux/amd64
  #   build: ./hive/
  #   container_name: oreilly_iceberg_hivemetastore
  #   command: "sh /run_metastore.sh"
  #   ports:
  #     - "9083:9083"
  #   volumes:
  #     - type: bind
  #       source: ../_data
  #       target: /usr/local/hadoop/warehouse

  jupyter:
    build: ./jupyter/
    container_name: oreilly_iceberg_jupyter
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: ../_data
        target: /usr/local/hadoop/warehouse
      - type: bind
        source: ../_notebooks
        target: /_oreilly_iceberg/notebooks

  # trino:
  #   build: ./trino/
  #   container_name: oreilly_iceberg_trino
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - type: bind
  #       source: ../_data
  #       target: /usr/local/hadoop/warehouse
  #     - type: bind
  #       source: ./trino/config
  #       target: /etc/trino/

