FROM alpine:3.14

ENV LANG=en_US.UTF-8
RUN apk add --no-cache linux-pam \
                       build-base \
                       musl-dev \
                       libffi-dev \
                       openssl-dev \
                       cargo \
                       python3 \
                       py3-pip \
                       python3-dev \
                       py3-cryptography \
                       nodejs \
                       npm
RUN pip3 install --no-cache jupyterhub==1.4.2
RUN npm install -g configurable-http-proxy
#RUN touch /jupyterhub_cookie_secret
#RUN chmod 600 /jupyterhub_cookie_secret

#USER nobody
#CMD ["which", "configurable-http-proxy"]
CMD ["jupyterhub"]
